name: terraform-destroy
on:
  repository_dispatch:
    types: [destroy]

env:
  TF_VAR_project: ${{secrets.PROJECT}}
  GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_CREDENTIALS}}

jobs:
  terraform-destroy:
    name: terraform-destroy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.5

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan Destroy
        id: plan
        run: terraform plan -destroy

      - name: Terraform Apply Destroy
        if: github.ref == 'refs/heads/master'
        run: terraform destroy -auto-approve
