name: 'terraform-destroy'
on:
  repository_dispatch:
    types: [destroy]

env:
  TERRAFORM_VERSION: 0.12.24
  TF_VAR_project: ${{secrets.PROJECT}}
  GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_CREDENTIALS}}
  
jobs:
  terraform:
    name: 'terraform-apply'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v1
        
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.24
          tf_actions_subcommand: 'init'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Terraform Plan Destroy'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.24
          tf_actions_subcommand: 'plan'
          args: '-destroy -out=./destroy-plan'

      - name: 'Terraform Apply Destroy'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.24
          tf_actions_subcommand: 'apply'
          args: './destroy-plan'
